# Book settings
title: Project Template
author: Development Data Partnership
logo: images/logo.png

repository:
    url: https://github.com/datapartnership/template
    branch: master  
  
html:
    favicon: images/favicon.ico
    home_page_in_navbar: true
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.org/
